const KEY='expiry-products-v1';let products=JSON.parse(localStorage.getItem(KEY)||'[]');
const $=id=>document.getElementById(id);const today=new Date();today.setHours(0,0,0,0);
$('today').textContent=today.toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'});
function daysLeft(date){const d=new Date(date+'T00:00:00');return Math.ceil((d-today)/86400000)}
function status(p){const d=daysLeft(p.expiry);if(d<0)return ['is-expired','已过期'];if(d<=15)return ['urgent','紧急'];if(d<=45)return ['soon','临期'];return ['normal','正常']}
function save(){localStorage.setItem(KEY,JSON.stringify(products));render()}
function render(){const q=$('search').value.trim().toLowerCase(),f=$('filter').value;let shown=products.filter(p=>{const s=status(p)[0];const match=!q||[p.name,p.category,p.sku,p.location,p.note].join(' ').toLowerCase().includes(q);const fm=f==='all'||(f==='expiring'&&(s==='soon'||s==='urgent'))||(f==='urgent'&&s==='urgent')||(f==='expired'&&s==='is-expired')||(f==='normal'&&s==='normal');return match&&fm});
 $('total').textContent=products.length;$('expiring').textContent=products.filter(p=>daysLeft(p.expiry)>=0&&daysLeft(p.expiry)<=45).length;$('urgent').textContent=products.filter(p=>daysLeft(p.expiry)>=0&&daysLeft(p.expiry)<=15).length;$('expired').textContent=products.filter(p=>daysLeft(p.expiry)<0).length;
 $('productRows').innerHTML=shown.sort((a,b)=>daysLeft(a.expiry)-daysLeft(b.expiry)).map(p=>{const [cls,label]=status(p),d=daysLeft(p.expiry);let left=d<0?`过期 ${Math.abs(d)} 天`:d===0?'今天到期':`还剩 ${d} 天`;return `<tr><td><div class="product-name">${esc(p.name)}</div><div class="sub">${esc(p.sku||'')}${p.location?' · 货架 '+esc(p.location):''}</div></td><td>${esc(p.category||'—')}</td><td>${p.quantity}</td><td>${p.expiry}</td><td><strong>${left}</strong></td><td><span class="badge ${cls}">${label}</span></td><td class="actions"><button onclick="editProduct('${p.id}')">编辑</button><button onclick="removeProduct('${p.id}')">删除</button></td></tr>`}).join('');$('empty').style.display=shown.length?'none':'block'}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openForm(p=null){$('dialogTitle').textContent=p?'编辑商品':'添加商品';$('productId').value=p?.id||'';$('name').value=p?.name||'';$('category').value=p?.category||'';$('sku').value=p?.sku||'';$('quantity').value=p?.quantity??1;$('expiry').value=p?.expiry||'';$('location').value=p?.location||'';$('note').value=p?.note||'';$('productDialog').showModal()}
window.editProduct=id=>openForm(products.find(p=>p.id===id));window.removeProduct=id=>{if(confirm('确定删除这个商品吗？')){products=products.filter(p=>p.id!==id);save()}};
$('addBtn').onclick=()=>openForm();$('cancelBtn').onclick=()=>$('productDialog').close();$('closeDialog').onclick=()=>$('productDialog').close();$('search').oninput=render;$('filter').onchange=render;
$('productForm').onsubmit=e=>{e.preventDefault();const data={id:$('productId').value||crypto.randomUUID(),name:$('name').value.trim(),category:$('category').value.trim(),sku:$('sku').value.trim(),quantity:Number($('quantity').value),expiry:$('expiry').value,location:$('location').value.trim(),note:$('note').value.trim()};const i=products.findIndex(p=>p.id===data.id);if(i>=0)products[i]=data;else products.push(data);save();$('productDialog').close()};
$('notifyBtn').onclick=async()=>{if(!('Notification'in window)){alert('当前浏览器不支持通知');return}const permission=await Notification.requestPermission();if(permission==='granted'){const count=products.filter(p=>daysLeft(p.expiry)>=0&&daysLeft(p.expiry)<=45).length;new Notification('临期管家',{body:count?`目前有 ${count} 个商品在45天内到期。`:'目前没有45天内到期的商品。'});$('notifyBtn').textContent='✓ 提醒已开启'}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
